# Generated by Django 4.2.3 on 2023-07-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdsh_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
    ]
